language: ruby
rvm:
- 2.7.0

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

