# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Sánchez Crespillo
description: > # this means to ignore newlines until "baseurl:"
  Personal site
baseurl: "/david" # the subpath of your site, e.g. /blog
url: "http://sanchezcrespillo.info/david" # the base hostname & protocol for your site

exclude: [Gemfile, Gemfile.lock, vendor]

# Build settings
markdown: kramdown

menu:
          - title: Dev
            url: ""
            items:
            - title: LT Words
              url: /ltWords/web/index
            - title: Labas Rytas
              url: /labasrytas/
            - title: VKWebEdit
              url: /vkwebedit
          - title: Music
            url: ""
            items:
            - url: /kd2x3.html
              title: KD2X3
            - url: /canciones_de_campamento.html
              title: Canciones de Campamento
            - url: /retalls.html
              title: Retalls
          - title: CV
            url: /cv.html
          - title: Blog
            url: /blog.html

social:
          - title: Blog
            url: /blog.html
            image: /media/img/button_blog.png
          - title: CV
            url: /cv.html
            image: /media/img/button_cv.png
          - title: LinkedIn
            url: https://www.linkedin.com/in/davidsanchezcrespillo
            image: /media/img/linkedin.png
          - title: Facebook
            url: https://www.facebook.com/davidsanchezcrespillo
            image: /media/img/facebook.png
          - title: Twitter
            url: https://www.twitter.com/dinopmi
            image: /media/img/twitter.png
          - title: Github
            url: https://github.com/davidsanchezcrespillo
            image: /media/img/github.png
          - title: StackOverflow
            url: https://stackoverflow.com/users/224368/dinopmi
            image: /media/img/stackoverflow.png

footer:
          - title: HTML5
            url: https://validator.w3.org/check?uri=referer
            image: /media/img/html5_valid.png
          - title: Made with Jekyll
            url: https://jekyllrb.com/
            image: /media/img/jekyll.png

publications:
           - title: Construyendo la web de un Instituto de Educación Secundaria
             authors: David Sánchez Crespillo
             date: April 2008
             where: Congrés Internacional Virtual d’Educació CIVE 2008 (Palma de Mallorca, Spain)
           - title: <a href="http://ieeexplore.ieee.org/xpl/freeabs_all.jsp?tp=&arnumber=1028820&isnumber=22105">Visualization for cooperative architecture design system</a>
             authors: Yuhua Luo - Sanchez, D. - Bennasar, A. - Fornes, J. - Serra, J.C. - Huescar, J.M.
             date: November 2002
             where: Sixth International Conference on Information Visualisation, 2002. Proceedings.
           - title:   A Remote Cooperative Desing System Using Interactive 3D Graphics 
             authors: Luo, L.; Galli, R.; Sánchez, D.; Bennàsar, A.; Fornés, J.; Serra, J. C.; Huéscar, J. M.; Gayà, J. 
             date: January 2001 
             where: "001289 - International Journal of Image and Graphics Vol: 1 Number: 1. Pages: 153 to 167 (Singapore)"
           - title: <a href="http://sanchezcrespillo.info/david/media/pdf/pdf_Stanford.pdf">A Cooperative Architecture Design System via Communication Network</a>
             authors: Yuhua Luo, Ricardo Galli, David Sánchez, Antonio Bennassar, Antonio Carlos Almeida, Miguel Dias
             date: August 2000 
             where: 8th International Conference on Computing in Civil and Building (Stanford University, Silicon Valley, CA, USA.)
           - title: <a href="http://sanchezcrespillo.info/david/media/pdf/pdf_iv2000.pdf">Implementation of Mechanisms for Concurrent 3D Design and Visualization</a>
             authors: David Sánchez Crespillo, Antonio Francisco Bennasar Obrador, Ricardo Galli Granada and Yuhua Luo 
             where: IEEE/International Conference on Information Visualisation (IV2000). London (United Kingdom)
             date: July 2000 
           - title:   The Multi-Site 3D Editing Tool For Architectural Production Integration 
             authors: David Sánchez, Toni Bennasar, Juan Fornés, Ricardo Galli, Juan Manuel Huéscar, Juan Carlos Serra, Yuhua Luo, Manuel Gamito, Miguel Dias, Marc Albiol, Juan Arias
             date: April 2000
             where: <a href="https://www.cordis.europa.eu/project/rcn/43395_en.html">ESPRIT Project No. 26287 M3D</a>, Deliverable 2.1. EC
           - title: <a href="http://sanchezcrespillo.info/david/media/pdf/pdf_Ast99.pdf">Sistema Cooperativo de Diseño en 3D</a>
             authors:   Yuhua Luo, Ricardo Galli, David Sánchez, Juan Fornés, Antonio Bennasar, Juan Carlos Serra, Juan Manuel Huéscar, Josep Gayà 
             date: December 1999 
             where:   I Seminario del Programa Nacional de Aplicaciones y Servicios Telemáticos (SPAST-I). Pamplona (Spain) 
           - title: Un editor 3D interactivo para trabajo cooperativo
             authors: David Sánchez Crespillo, Ricardo Galli, Yuhua Luo 
             date: June 1999 
             where: IX Congreso Español de Informática Gráfica. Jaén (Spain)
           - title: M3D technical specifications 
             authors: R.Galli, Y. Luo, D. Sánchez, S. Alves, M. Dias, R. Marques, A. Almeida, J. Silva, J. Manuel, B. Tummers 
             date: April 1999 
             where: <a href="https://www.cordis.europa.eu/project/rcn/43395_en.html">ESPRIT Project No. 26287 M3D</a>, Deliverable 1.2 
           - title:   M3D Prototype 
             authors: Marco Moita, Sérgio Alves, Renato Marques, Manuel Gamito, Jorge Silva, José Manuel Fonseca, Miguel Vilar, Ricardo Galli, David Sanchez, Yuhua Luo 
             date: April 1999 
             where: <a href="https://www.cordis.europa.eu/project/rcn/43395_en.html">ESPRIT Project No. 26287 M3D</a>, Deliverable 1.5
