# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Sánchez Crespillo
description: > # this means to ignore newlines until "baseurl:"
  Personal site
baseurl: "/david" # the subpath of your site, e.g. /blog
url: "http://sanchezcrespillo.info/david" # the base hostname & protocol for your site

exclude: [Gemfile, Gemfile.lock, vendor]

# Build settings
markdown: kramdown

menu:
          - title: Dev
            url: ""
            items:
            - title: LT Words
              url: /ltWords/web/index
            - title: Labas Rytas
              url: /labasrytas/
            - title: VKWebEdit
              url: /vkwebedit
          - title: Music
            url: ""
            items:
            - url: /kd2x3.html
              title: KD2X3
            - url: /canciones_de_campamento.html
              title: Canciones de Campamento
            - url: /retalls.html
              title: Retalls
          - title: CV
            url: /cv.html
          - title: Blog
            url: /blog.html

social:
          - title: LinkedIn
            url: http://www.linkedin.com/in/davidsanchezcrespillo
            image: /media/img/linkedin.png
          - title: Facebook
            url: http://www.facebook.com/davidsanchezcrespillo
            image: /media/img/facebook.png
          - title: Twitter
            url: https://www.twitter.com/dinopmi
            image: /media/img/twitter.png
          - title: Github
            url: https://github.com/davidsanchezcrespillo
            image: /media/img/github.png
          - title: StackOverflow
            url: http://stackoverflow.com/users/224368/dinopmi
            image: /media/img/stackoverflow.png

footer:
          - title: HTML5
            url: http://validator.w3.org/check?uri=referer
            image: /media/img/html5_valid.png
          - title: Made with Jekyll
            url: https://jekyllrb.com/
            image: /media/img/jekyll.png

